/**
 * Maps a free-text Philippine region/province name — as reported by a
 * marketplace's own address hierarchy, not the PSGC dataset's exact
 * strings — to the official PSGC region string this app uses everywhere
 * else (shipping zone lookup in shipping.ts, the storefront's own address
 * dropdown). Two tables, tried in order:
 *
 * 1. REGION_NAME_ALIASES — informal region names ("Central Luzon", "Ilocos",
 *    "Metro Manila"). Confirmed live against TikTok Shop's district_info:
 *    its L1 level (the broadest below country) reports the region this way,
 *    not the formal "REGION III (CENTRAL LUZON)" string — e.g. a real
 *    Pampanga order came back with L1 "Central Luzon", L2 "Pampanga"; a
 *    real Manila order came back with L1 "Metro Manila", L2 "Manila" (NCR
 *    has no province level, so its L2 lands on a city name instead).
 * 2. PROVINCE_TO_REGION — actual province names, generated from
 *    public/data/ph-address.json's Region → Province structure — a
 *    fallback for whatever ends up in L2, or a marketplace that reports a
 *    province directly rather than a region name.
 */
const REGION_NAME_ALIASES: Record<string, string | undefined> = {
  ILOCOS: 'REGION I (ILOCOS REGION)',
  'ILOCOS REGION': 'REGION I (ILOCOS REGION)',
  'CAGAYAN VALLEY': 'REGION II (CAGAYAN VALLEY)',
  'CENTRAL LUZON': 'REGION III (CENTRAL LUZON)',
  CALABARZON: 'REGION IV-A (CALABARZON)',
  MIMAROPA: 'MIMAROPA REGION',
  'SOUTHWESTERN TAGALOG': 'MIMAROPA REGION',
  'SOUTHWESTERN TAGALOG REGION': 'MIMAROPA REGION',
  BICOL: 'REGION V (BICOL REGION)',
  'BICOL REGION': 'REGION V (BICOL REGION)',
  'WESTERN VISAYAS': 'REGION VI (WESTERN VISAYAS)',
  'CENTRAL VISAYAS': 'REGION VII (CENTRAL VISAYAS)',
  'EASTERN VISAYAS': 'REGION VIII (EASTERN VISAYAS)',
  'ZAMBOANGA PENINSULA': 'REGION IX (ZAMBOANGA PENINSULA)',
  'NORTHERN MINDANAO': 'REGION X (NORTHERN MINDANAO)',
  DAVAO: 'REGION XI (DAVAO REGION)',
  'DAVAO REGION': 'REGION XI (DAVAO REGION)',
  SOCCSKSARGEN: 'REGION XII (SOCCSKSARGEN)',
  CARAGA: 'REGION XIII (Caraga)',
  CORDILLERA: 'CORDILLERA ADMINISTRATIVE REGION (CAR)',
  'CORDILLERA ADMINISTRATIVE REGION': 'CORDILLERA ADMINISTRATIVE REGION (CAR)',
  CAR: 'CORDILLERA ADMINISTRATIVE REGION (CAR)',
  BANGSAMORO: 'BANGSAMORO AUTONOMOUS REGION (BARMM)',
  'BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO':
    'BANGSAMORO AUTONOMOUS REGION (BARMM)',
  BARMM: 'BANGSAMORO AUTONOMOUS REGION (BARMM)',
  ARMM: 'BANGSAMORO AUTONOMOUS REGION (BARMM)',
  'METRO MANILA': 'NATIONAL CAPITAL REGION (NCR)',
  NCR: 'NATIONAL CAPITAL REGION (NCR)',
  'NATIONAL CAPITAL REGION': 'NATIONAL CAPITAL REGION (NCR)',
}

const PROVINCE_TO_REGION: Record<string, string | undefined> = {
  'ILOCOS NORTE': 'REGION I (ILOCOS REGION)',
  'ILOCOS SUR': 'REGION I (ILOCOS REGION)',
  'LA UNION': 'REGION I (ILOCOS REGION)',
  PANGASINAN: 'REGION I (ILOCOS REGION)',
  BATANES: 'REGION II (CAGAYAN VALLEY)',
  CAGAYAN: 'REGION II (CAGAYAN VALLEY)',
  ISABELA: 'REGION II (CAGAYAN VALLEY)',
  'NUEVA VIZCAYA': 'REGION II (CAGAYAN VALLEY)',
  QUIRINO: 'REGION II (CAGAYAN VALLEY)',
  BATAAN: 'REGION III (CENTRAL LUZON)',
  BULACAN: 'REGION III (CENTRAL LUZON)',
  'NUEVA ECIJA': 'REGION III (CENTRAL LUZON)',
  PAMPANGA: 'REGION III (CENTRAL LUZON)',
  TARLAC: 'REGION III (CENTRAL LUZON)',
  ZAMBALES: 'REGION III (CENTRAL LUZON)',
  AURORA: 'REGION III (CENTRAL LUZON)',
  BATANGAS: 'REGION IV-A (CALABARZON)',
  CAVITE: 'REGION IV-A (CALABARZON)',
  LAGUNA: 'REGION IV-A (CALABARZON)',
  QUEZON: 'REGION IV-A (CALABARZON)',
  RIZAL: 'REGION IV-A (CALABARZON)',
  MARINDUQUE: 'MIMAROPA REGION',
  'OCCIDENTAL MINDORO': 'MIMAROPA REGION',
  'ORIENTAL MINDORO': 'MIMAROPA REGION',
  PALAWAN: 'MIMAROPA REGION',
  ROMBLON: 'MIMAROPA REGION',
  ALBAY: 'REGION V (BICOL REGION)',
  'CAMARINES NORTE': 'REGION V (BICOL REGION)',
  'CAMARINES SUR': 'REGION V (BICOL REGION)',
  CATANDUANES: 'REGION V (BICOL REGION)',
  MASBATE: 'REGION V (BICOL REGION)',
  SORSOGON: 'REGION V (BICOL REGION)',
  AKLAN: 'REGION VI (WESTERN VISAYAS)',
  ANTIQUE: 'REGION VI (WESTERN VISAYAS)',
  CAPIZ: 'REGION VI (WESTERN VISAYAS)',
  ILOILO: 'REGION VI (WESTERN VISAYAS)',
  'NEGROS OCCIDENTAL': 'REGION VI (WESTERN VISAYAS)',
  GUIMARAS: 'REGION VI (WESTERN VISAYAS)',
  BOHOL: 'REGION VII (CENTRAL VISAYAS)',
  CEBU: 'REGION VII (CENTRAL VISAYAS)',
  'NEGROS ORIENTAL': 'REGION VII (CENTRAL VISAYAS)',
  SIQUIJOR: 'REGION VII (CENTRAL VISAYAS)',
  'EASTERN SAMAR': 'REGION VIII (EASTERN VISAYAS)',
  LEYTE: 'REGION VIII (EASTERN VISAYAS)',
  'NORTHERN SAMAR': 'REGION VIII (EASTERN VISAYAS)',
  'SAMAR (WESTERN SAMAR)': 'REGION VIII (EASTERN VISAYAS)',
  'SOUTHERN LEYTE': 'REGION VIII (EASTERN VISAYAS)',
  BILIRAN: 'REGION VIII (EASTERN VISAYAS)',
  'ZAMBOANGA DEL NORTE': 'REGION IX (ZAMBOANGA PENINSULA)',
  'ZAMBOANGA DEL SUR': 'REGION IX (ZAMBOANGA PENINSULA)',
  'ZAMBOANGA SIBUGAY': 'REGION IX (ZAMBOANGA PENINSULA)',
  BUKIDNON: 'REGION X (NORTHERN MINDANAO)',
  CAMIGUIN: 'REGION X (NORTHERN MINDANAO)',
  'LANAO DEL NORTE': 'REGION X (NORTHERN MINDANAO)',
  'MISAMIS OCCIDENTAL': 'REGION X (NORTHERN MINDANAO)',
  'MISAMIS ORIENTAL': 'REGION X (NORTHERN MINDANAO)',
  'DAVAO DEL NORTE': 'REGION XI (DAVAO REGION)',
  'DAVAO DEL SUR': 'REGION XI (DAVAO REGION)',
  'DAVAO ORIENTAL': 'REGION XI (DAVAO REGION)',
  'COMPOSTELA VALLEY': 'REGION XI (DAVAO REGION)',
  'DAVAO OCCIDENTAL': 'REGION XI (DAVAO REGION)',
  'COTABATO (NORTH COTABATO)': 'REGION XII (SOCCSKSARGEN)',
  'SOUTH COTABATO': 'REGION XII (SOCCSKSARGEN)',
  'SULTAN KUDARAT': 'REGION XII (SOCCSKSARGEN)',
  SARANGANI: 'REGION XII (SOCCSKSARGEN)',
  ABRA: 'CORDILLERA ADMINISTRATIVE REGION (CAR)',
  BENGUET: 'CORDILLERA ADMINISTRATIVE REGION (CAR)',
  IFUGAO: 'CORDILLERA ADMINISTRATIVE REGION (CAR)',
  KALINGA: 'CORDILLERA ADMINISTRATIVE REGION (CAR)',
  'MOUNTAIN PROVINCE': 'CORDILLERA ADMINISTRATIVE REGION (CAR)',
  APAYAO: 'CORDILLERA ADMINISTRATIVE REGION (CAR)',
  BASILAN: 'BANGSAMORO AUTONOMOUS REGION (BARMM)',
  'LANAO DEL SUR': 'BANGSAMORO AUTONOMOUS REGION (BARMM)',
  MAGUINDANAO: 'BANGSAMORO AUTONOMOUS REGION (BARMM)',
  SULU: 'BANGSAMORO AUTONOMOUS REGION (BARMM)',
  'TAWI TAWI': 'BANGSAMORO AUTONOMOUS REGION (BARMM)',
  'AGUSAN DEL NORTE': 'REGION XIII (Caraga)',
  'AGUSAN DEL SUR': 'REGION XIII (Caraga)',
  'SURIGAO DEL NORTE': 'REGION XIII (Caraga)',
  'SURIGAO DEL SUR': 'REGION XIII (Caraga)',
  'DINAGAT ISLANDS': 'REGION XIII (Caraga)',
}

/** Tries the region-name table first (matches TikTok's L1 district_info
 *  level), then the province table (matches its L2, or a marketplace that
 *  reports a province directly). Null if neither matches — callers should
 *  treat that as "unknown," not guess a default. */
export function resolveOfficialRegion(name: string): string | null {
  const normalized = name.trim().toUpperCase()
  if (!normalized) return null
  return REGION_NAME_ALIASES[normalized] ?? PROVINCE_TO_REGION[normalized] ?? null
}
